// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Task struct {
	ID        pgtype.UUID
	Name      string
	Trigger   []byte
	Action    []byte
	Status    string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	NextRun   pgtype.Timestamptz
}

type TaskResult struct {
	ID              pgtype.UUID
	TaskID          pgtype.UUID
	RunAt           pgtype.Timestamptz
	StatusCode      int32
	Success         bool
	ResponseHeaders []byte
	ResponseBody    []byte
	ErrorMessage    pgtype.Text
	DurationMs      int32
	CreatedAt       pgtype.Timestamptz
}
